[build]
command = "npm install && npm run build"
functions = "functions"

[functions]
external_node_modules = ["express"]
included_files = ["./functions/index.html"]
node_bundler = "esbuild"

[[redirects]]
from = "/*"
to = "/.netlify/functions/api/:splat"
status = 200
force = true
